Repository ics-creative/160609_animation-image-generator, pull requests merged in 2022-02, with the labels that each got.

#23 移行でデグレした箇所の修正
  product/src/app/components/app/app.html
  product/src/app/components/app/checkImagePxSizeMatched.ts
  product/src/app/process/ipc.service.ts
Labels: Problem:Bug, Type:Refactoring

#20 画像選択・再選択を複数回行うと動作しない問題の修正
  product/dist-config/main-src/main.js
  product/main-src/main.ts
  product/src/app/components/app/app.ts
  product/src/app/process/ServiceEvent.ts
  product/src/app/process/ipc.service.ts
Labels: Problem:Bug

#25 プロセス間通信の非同期化と型情報付与
  product/common-src/ipc-id.ts
  product/dist-config/common-src/ipc-id.js
  product/dist-config/main-src/main.js
  product/dist-config/preload.js
  product/main-src/main.ts
  product/src/app/components/app/app.html
  product/src/app/components/app/app.ts
  product/src/app/process/ipc.service.ts
Labels: Problem:Bug, Type:Refactoring

#26 ビルドしたアプリが起動できるようにする＆ビルド処理のリファクタリング
  product/angular.json
  product/build-scripts/common.js
  product/build-scripts/conf.js
  product/build-scripts/copy-assets-to-dist.js
  product/build-scripts/copy-binary-assets.js
  product/build-scripts/copy-debug-assets.js
  product/build-scripts/for-mac-packaging.js
  product/build-scripts/for-mac-prebuild.js
  product/build-scripts/for-windows-packaging.js
  product/build-scripts/for-windows-prebuild.js
  product/dist-config/bin/apngasm
  product/dist-config/bin/cwebp
  product/dist-config/bin/pngquant
  product/dist-config/bin/webpmux
  product/dist-config/common-src/config/app-config.js
  product/dist-config/common-src/data/animation-image-option.js
  product/dist-config/common-src/data/image-data.js
  product/dist-config/common-src/error/error-type.js
  product/dist-config/common-src/i18n/locale-data.interface.js
  product/dist-config/common-src/ipc-id.js
  product/dist-config/common-src/preset/preset-line.js
  product/dist-config/common-src/preset/preset-web.js
  product/dist-config/common-src/type/CompressionType.js
  product/dist-config/common-src/type/PresetType.js
  product/dist-config/common-src/validators/LineStampValidator.js
  product/dist-config/delete-file.js
  product/dist-config/main-src/delete-file.js
  product/dist-config/main-src/dialog/SaveDialog.js
  product/dist-config/main-src/dialog/openSaveDialog.js
  product/dist-config/main-src/error/error-message.js
  product/dist-config/main-src/error/send-error.js
  product/dist-config/main-src/file.js
  product/dist-config/main-src/fileFunctions/deleteDirectory.js
  product/dist-config/main-src/fileFunctions/deleteFile.js
  product/dist-config/main-src/fileFunctions/emptyDirectory.js
  product/dist-config/main-src/fileFunctions/execFile.js
  product/dist-config/main-src/fileFunctions/exists.js
  product/dist-config/main-src/fileFunctions/existsPath.js
  product/dist-config/main-src/fileFunctions/getExeExt.js
  product/dist-config/main-src/generates/generateHtml.js
  product/dist-config/main-src/generators/GenerateError.js
  product/dist-config/main-src/generators/createInquiryCode.js
  product/dist-config/main-src/generators/execGenerate.js
  product/dist-config/main-src/generators/generateApng.js
  product/dist-config/main-src/generators/generateHtml.js
  product/dist-config/main-src/generators/generateWebp.js
  product/dist-config/main-src/main.js
  product/dist-config/main-src/menu/application-menu.js
  product/dist-config/main-src/utils/notNull.js
  product/dist-config/main-src/utils/timer.js
  product/dist-config/package.json
  product/dist-config/src/app/config/app-config.js
  product/dist-config/src/app/data/animation-image-option.js
  product/dist-config/src/app/i18n/locale-data.js
  product/main-src/generators/createInquiryCode.ts
  product/main-src/main.ts
  product/main-src/tsconfig.json
  product/package-lock.json
  product/package.json
Labels: Type:Refactoring, Type:Migration

#33 メインプロセスをViteでバンドル＆エラー送信が動作するように修正
  product/build-scripts/clear-build.js
  product/build-scripts/common.js
  product/build-scripts/for-mac-prebuild.js
  product/main-src/error/send-error.ts
  product/main-src/file.ts
  product/main-src/main.ts
  product/main-src/tsconfig.json
  product/main-src/vite.config.ts
  product/package-lock.json
  product/package.json
Labels: Problem:Bug, dependencies, Type:Refactoring, Type:Migration

#36 Fix/35 windows alert title
  product/build-scripts/for-windows-packaging.js
  product/build-scripts/for-windows-store-packaging.js
  product/common-src/config/app-config.ts
  product/common-src/ipc-id.ts
  product/main-src/main.ts
  product/src/app/components/app/app.ts
  product/src/app/i18n/locale-en.ts
  product/src/app/process/ipc.service.ts
Labels: Problem:Bug

#39 起動時に稀に空白のウインドウが表示されてハングする問題の修正
  product/main-src/main.ts
Labels: Problem:Bug

#42 拡張子の大文字も対応
  product/src/app/components/app/app.ts
Labels: Problem:Bug

#41 アナリティクスが記録されない問題を修正
  product/common-src/config/app-config.ts
  product/main-src/main.ts
  product/src/app/components/app/app.html
  product/src/app/components/app/app.ts
  product/src/main.ts
Labels: Problem:Bug, Type:Migration

#40 Windows Store用ビルドのための設定修正
  product/AppXManifest.xml
  product/build-scripts/conf.js
  product/build-scripts/for-windows-store-packaging.js
Labels: Type:Release
